### ISSUE TITLE
crash after first-open of mpq explorer

### ISSUE THREAD

**Issue by gucio321** [OpenDiablo2/HellSpawner#136]
Hi there,
I found a bug: when we add new auxiliary mpq's and then we open mpq explorer, app is crashing.
**STEPS TO REPRODUCE:**
- "remove" hellspawner's config file (for me /home/username/.config/hellspawner/environment.json)
- open HellSpawner and go to file->preferences
- set auxiliary MPQ path
- open some project
- go to project->properities->add auxiliary MPQ
- select some MPQ
- open MPQ Explorer
- and then.... we have 
```golang
2021/01/12 18:36:57 open d2char.mpq: no such file or directory
exit status 1
```

**Comment by ianling** [comment]
I am working on this
