### ISSUE TITLE
mpq viewer: patch_d2.mpq

### ISSUE THREAD

**Issue by gucio321** [OpenDiablo2/HellSpawner#146]
**Describe the bug**
Unable to view patch_d2.mpq's content

**To Reproduce**
1. open project and add patch_d2.mpq
2. open mpq viewer
3. cannot to view files in archive

**Screenshots**
![image](https://user-images.githubusercontent.com/73652197/104633363-51608180-569f-11eb-9468-c08d776cd996.png)

**Comment by Ziemas** [comment]
patch_d2.mpq does not have an internal file list, an external list is needed to find files in it. Get the archive of listfiles from http://www.zezula.net/en/mpq/download.html and add the D2 one to HellSpawner in the preferences.
