### ISSUE TITLE
Output logs to Console tool window, and file

### ISSUE THREAD

**Issue by ianling** [OpenDiablo2/HellSpawner#164]
Most users of HellSpawner probably won't be running it from a terminal/console window, so they won't be able to see any log messages.

Log messages should get sent to the Console tool window in HellSpawner.

Log messages should also get sent to a file in real time, so that we can retrieve logs for bug reports if HellSpawner crashes.

**Comment by madwizard** [comment]
Should this be configurable somehow? I mean, should user be able to choose where log files are sent, or should we assume location?
I'm thinking about extending OD2 logger to allow writing to a file.

**Comment by ianling** [comment]
IMO, it should be configurable, but we should have a default location, maybe in the same folder as the config?

If it's not already like this, maybe the OD2 logger could be extended to support just handing it any kind of IO object (not sure what it is called in golang off the top of my head), e.g. a file handle, stdout, etc. So that we can just tell the logger to log to both the file and the console at the same time.
