### ISSUE TITLE
When importing MPQ's, preserve selection order 

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/HellSpawner#199]
## Setting MPQ load-order is hard
Setting the order should be easy and intuitive.

## We should be able to select multiple MPQ's
When we're adding MPQ's to a project, we should be able to select more than one of them, and the order in which we select them should be reflected when the MPQ's are added to the project.

## Alternatives
The current implementation is the alternative; manually adding one-by-one, then manually raising/lowering the MPQ's one-by-one.

**Comment by gucio321** [comment]
I'm just on it, but I have a question:
> and the order in which we select them should be reflected when the MPQ's are added to the project.

does the MPQs order really metter? multiple selection is easy to do, but I don't see any reason to complicate code and add loading-order logic

**Comment by gravestench** [comment]
Well, the original idea was to show a "composite view" of the currently loaded MPQ's, much like how d2 uses the mpq's.

The order that you layer the MPQ's for a composite view does matter. This is how the patch files in `patch_d2.mpq` are favored over pre-existing files with the same file-path in other mpq's.
