### ISSUE TITLE
hsfiletypes.determineTBLtype doesn't work properly

### ISSUE THREAD

**Issue by gucio321** [OpenDiablo2/HellSpawner#259]
**Describe the bug**
Sometimes, while opening .tbl files of type StringTable (string.tbl) the app determinates its type as a font table and runs wrong editor

**To Reproduce**
1.open some project with aux MPQs
2. in mpq explorer go to d2data.mpq/data/local/lng/{come language e.g eng}
3. click on string.tbl
4. sometimes, you can see font table loading error

**Expected behavior**
every time, when you click on `string.tbl` the appropriate editor should be opened

**Screenshots**
![image](https://user-images.githubusercontent.com/73652197/113988151-73594280-984f-11eb-9573-97999c2841ab.png)

**Desktop (please complete the following information):**
 - OS: Fedora release 33 (Thirty Three)

**Comment by gravestench** [comment]
in `hsfiletypes/filetype.go`:
```golang
func fileExtensionInfo() map[FileType]fileTypeInfoStruct {
	return map[FileType]fileTypeInfoStruct{
		FileTypeUnknown:        {},
		FileTypeFont:           {Name: "Font", Extension: ".hsf"},
		FileTypePalette:        {Name: "Palette", Extension: ".dat"},
		FileTypePL2:            {Name: "Palette Map", Extension: ".pl2"},
		FileTypeAudio:          {Name: "Audio", Extension: ".wav"},
		FileTypeDCC:            {Name: "DCC", Extension: ".dcc"},
		FileTypeDC6:            {Name: "DC6", Extension: ".dc6"},
		FileTypeCOF:            {Name: "COF", Extension: ".cof"},
		FileTypeDT1:            {Name: "DT1", Extension: ".dt1"},
		FileTypeTBL:            {Name: "TBL", Extension: ".tbl", subTypeCheck: determineTBLtype},
		FileTypeTBLFontTable:   {Name: "Font table", Extension: ".tbl"},
		FileTypeTBLStringTable: {Name: "String table", Extension: ".tbl"},
		FileTypeText:           {Name: "Text", Extension: ".txt"},
		FileTypeDS1:            {Name: "DS1", Extension: ".ds1"},
		FileTypeAnimationData:  {Name: "AnimationData", Extension: ".d2"},
	}
}
```

The problem stems from the fact that you added `FileTypeTBLFontTable` and `FileTypeTBLStringTable` to this table, where both of those file types are sub-types of `FileTypeTBL` (they share a file extension).

If you look closely, you'll see that `determineTBLtype` is a function which determines the sub-type.
