### ISSUE TITLE
Unexpected behavior when double/triple/N clicking a file in the MPQ Explorer

### ISSUE THREAD

**Issue by bbrucee** [OpenDiablo2/HellSpawner#314]
## Describe the bug
When a user double/triple/N clicks a file in the MPQ Explorer, the widget is constructed in an unexpected way

## To Reproduce
1. Open the MPQ Explorer
2. Navigate to a file
3. Click the file more than once

## Expected behavior
The expected behavior should be to generate a widget with the same elements as when generated after a single click

## Screenshots
![Animation_2](https://user-images.githubusercontent.com/13605787/121107084-4c7aa680-c7d5-11eb-99a0-1e90939fb8e0.gif)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Go version go1.16.4 windows/amd64
 - Ryzen 5600X (Issue depends on system performance)

## Additional context
The weird part is that it does stop you from opening a second widget of the same file so it seems like the bug is that it will run the create widget method for each click prior to the widget being loaded
Might be tied to the the GIU widget id?

**Comment by bbrucee** [comment]
After investigation it looks like the culprit of the bug is the management of the editorManagerMutex https://github.com/OpenDiablo2/HellSpawner/blob/master/hsapp/app.go#L222 

The issue appears to be on fast machines, multiple openEditor calls will fire and process such that concurrent executions of the createEditor method reach the lock on L222. This leads to the a.editors list containing multiple entries with the same unique ID.

**Comment by bbrucee** [comment]
My proposed change is to move the lock acquire from L222 to the beginning of CreateEditor. This will enforce that only one createEditor call will be fired for any given Unique ID. The RLock in the openEditor method will no longer be acquired when a concurrent execution of CreateEditor is generating the editor as opposed to the current behavior where the RLock gets acquired allowing multiple CreateEditors to reach the a.editors = append... line on 224 

Edit: This causes the RestoreApp functionality to become laggy as it has to wait to generate each editor object

**Comment by gravestench** [comment]
I think your proposed solution is good enough, I don't think it's a big deal for there to be some reasonable delays during app start. A "reasonable" delay would be ~2 second startup for an existing project with some editors opened.
