### ISSUE TITLE
DT1 editor: setting palette does not work

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/HellSpawner#334]
## Describe the bug
Setting a palette for the DT1 (tileset) editor does not work. tested on master.

## To Reproduce

1) Open a DT1 file
2) in the DT1 menu (in the main menu bar), click "Change Palette"
3) select a ".dat" palette file

## Expected behavior
The palette for the displayed tileset should change

## Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.4
 - Go version 1.16.5

https://user-images.githubusercontent.com/936440/127200270-234fa480-1f47-4e47-b570-99cadb663eee.mov

<img width="216" alt="Screen Shot 2021-07-27 at 10 27 26 AM" src="https://user-images.githubusercontent.com/936440/127200281-eaeb5b6f-9995-4d26-98c9-34a1f0532b3d.png">

**Comment by gucio321** [comment]
hmm, are you really sure you're testing on upstream/master?
I cant reproduce the behavior
![image](https://user-images.githubusercontent.com/73652197/127378531-6aaa1565-42a7-4965-916e-c5821ae0ae28.png)

**Comment by gravestench** [comment]
Yes, I think I forgot to switch back to master, thanks!
