### ISSUE TITLE
Creating a new project appends the extension again

### ISSUE THREAD

**Issue by b4sen** [OpenDiablo2/HellSpawner#337]
## Describe the bug
When creating a new project, the `.hsp` extension gets appended again resulting in a filename of `xxx.hsp.hsp`

## To Reproduce
1. Create a new project

## Expected behavior
The filename should have the extension only once

## Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.5
 - Go version 1.16

**Comment by gravestench** [comment]
Thanks for reporting. As per our chat on discord, assigning to you.
