### ISSUE TITLE
Ubuntu 20 - go.sub "malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by harn3ss** [OpenDiablo2/HellSpawner#340]
## Describe the bug
Ubuntu fails to git D/L and build on cloned master repo

## To Reproduce
1) Fresh install of latest golang from apt-get
2) Run build.sh script

## Expected behavior
Git download and build from go.mod

## Screenshots
https://imgur.com/a/rXsDf4i

## Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20
 - Go version go version go1.13.8 linux/amd64

## Config (your config file):

<details><summary>config file</summary><br><pre>
build github.com/OpenDiablo2/HellSpawner: cannot load embed: malformed module path "embed": missing dot in first path element
</pre></details>

**Comment by gravestench** [comment]
We require go v1.16 (see `go.mod`)
